export const colors = {
  BORDER_RADIUS : 13,
  BACKGROUND_COLOR_LIGHT : 'white',
  BACKGROUND_COLOR_DARK : '#0E0E0E',
  BORDER_COLOR : '#d5d5d5',
  TITLE_FONT_SIZE : 13,
  TITLE_COLOR : '#8f8f8f',
  BUTTON_FONT_WEIGHT : 'normal',
  BUTTON_FONT_COLOR : '#007ff9',
  BUTTON_FONT_SIZE : 20,
  HIGHLIGHT_COLOR : '#ebebeb',
};

